# encoding: UTF-8

FROM <%= ENV.fetch('FROM') %>
MAINTAINER The Blue Beluga <admin@bluebeluga.io>

LABEL vendor="The Blue Beluga Company"
LABEL io.bluebeluga.geminabox.description="Gem-in-a-box"
LABEL io.bluebeluga.geminabox.version="<%= ENV.fetch('TAG') %>"
LABEL io.bluebeluga.geminabox.git-revision="<%= ENV.fetch('GIT_REVISION') %>"
LABEL io.bluebeluga.geminabox.release-date="<%= Time.now.strftime('%B %d, %Y %H:%M') %>"

RUN apk-install --virtual build-dependencies build-base && \
    gem install geminabox && \
    apk del build-dependencies build-base && \
    rm -rf /var/cache/apk/* && \
    mkdir /data

COPY files/config.ru /
RUN chown -R nobody:nogroup /data
USER nobody

VOLUME ["/data"]

EXPOSE 9293

ENTRYPOINT ["bundle", "exec", "rackup"]
CMD ["--host", "0.0.0.0", "-p", "9293", "-s", "thin", "/config.ru"]
